---
- name: kube-node demo
  hosts: all

  tasks:
  - name: copy file from ansible-server to kube-node
    copy: src=/root/demo-spring-pod.yml dest=/root
    copy: src=/root/demo-spring-svc.yml dest=/root

  - name: create a pod using demo-spring-pod.yml
    command: minikube kubectl -- apply -f /root/demo-spring-pod.yml

  - name: create a service using demo-spring-svc.yml
    command: minikube kubectl -- apply -f /root/demo-spring-svc.yml

  - name: start proxy server on minikube
    command: minikube kubectl -- proxy --address='0.0.0.0' --disable-filter=true
    ignore_errors: yes

