---
- name: Docker build demo 1
  hosts: 127.0.0.1
  connection: local
  
  tasks:
  - name: build a docker image with deployed jar file
    command: docker build -t xxx/demo-spring-ansible .
    args:
        chdir: /root
    ignore_errors: yes

  - name: Login to Docker Hub Registry 
    command: docker login -u xxx -p xxx
    ignore_errors: yes
    
  - name: upload image to Docker Hub Registry 
    command: docker push xxx/demo-spring-ansible
    ignore_errors: yes
