---
- name: Docker build demo 1
  hosts: 127.0.0.1
  connection: local
  
  tasks:
  - name: build a docker image with deployed jar file
    command: docker build -t demo-spring-ansible .
    args:
        chdir: /root
        
  - name: create a container using demo-spring-ansible image
    command: docker run -d --name demo-spring -p 9090:9090 demo-spring-ansible